"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',  # Add DRF
    'rest_framework_simplejwt',
    'api',             # Add your app
    'corsheaders',  # Add this - must be before other apps

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add this - must be near top
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # For browsable API
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': None,  # We'll add pagination in Level 2
    'DEFAULT_THROTTLE_CLASSES': [
        # AnonRateThrottle: Throttles unauthenticated users by IP address
        'rest_framework.throttling.AnonRateThrottle',
        # UserRateThrottle: Throttles authenticated users by user ID
        'rest_framework.throttling.UserRateThrottle'
    ],
    # Rate limits for each throttle class
    # Keys must match the 'scope' of throttle classes
    'DEFAULT_THROTTLE_RATES': {
        # 'anon' = scope for AnonRateThrottle
        # 100 requests per hour for anonymous (unauthenticated) users
        'anon': '100/hour',
        # 'user' = scope for UserRateThrottle
        # 1000 requests per hour for authenticated users
        'user': '1000/hour',

        'burst': '60/min',
        'sustained': '1000/day'},
        
    'NUM_PROXIES': 1, 
    'DEFAULT_FILTER_BACKENDS': [
        # DjangoFilterBackend: Handles filtering with django-filter (exact matches, ranges, etc.)
        'django_filters.rest_framework.DjangoFilterBackend',
        # SearchFilter: Handles searching across multiple fields (built into DRF)
        'rest_framework.filters.SearchFilter',
        # OrderingFilter: Handles sorting results (built into DRF)
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT ={
    # How long access token is valid (short = more secure, but users need to refresh more often)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    
    # How long refresh token is valid (longer = users stay logged in longer)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    
    # Security: Issue new refresh token when old one is used (prevents token reuse)
    'ROTATE_REFRESH_TOKENS': True,
    
    # Security: Add old refresh token to blacklist after rotation (prevents reuse)
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Track when user last logged in (useful for security monitoring)
    'UPDATE_LAST_LOGIN': True,
    
    # Algorithm to sign tokens (HS256 = HMAC SHA-256, fast and secure)
    'ALGORITHM': 'HS256',
    
    # Secret key to sign tokens (use Django's SECRET_KEY for security)
    'SIGNING_KEY': SECRET_KEY,
    
    # Token type in Authorization header (Bearer is standard OAuth2 format)
    'AUTH_HEADER_TYPES': ('Bearer',),
    
    # Header name where token is sent (HTTP_AUTHORIZATION = "Authorization: Bearer <token>")
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    
    # Which User model field to use as user ID (usually 'id')
    'USER_ID_FIELD': 'id',
    
    # Where to store user ID in token payload (used when decoding token)
    'USER_ID_CLAIM': 'user_id',
}