# Generated by Django 6.0.2 on 2026-02-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
