# Generated by Django 6.0.2 on 2026-02-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_task_3b_priority_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='task',
        ),
        migrations.AddField(
            model_name='task_3b',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category'),
        ),
        migrations.AddField(
            model_name='task_3b',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='api.priority'),
        ),
    ]
